// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://innbpfeexfdnkzfkacgi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlubmJwZmVleGZkbmt6ZmthY2dpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyNDUwNTMsImV4cCI6MjA2NzgyMTA1M30.Y9lseg0KkYdMVg8wx2HuQTBBh70wdK30y7qiRk5phrI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});